- hosts: haproxys

  vars:
    haproxy_app_name: http_web
    haproxy_mode: http
    haproxy_backend: rgw
    haproxy_backend_servers:
      - {name: rgw1, ip: 10.8.129.01, port: 8080, paramstring: check}
      - {name: rgw2, ip: 10.8.129.10, port: 8080, paramstring: check}
    frontend_port: 80

  tasks:
    - name: install haproxy
      yum: name=haproxy state=present

    - name: Create HAProxy-http xml
      template: src=templates/haproxy-http.cfg
           dest=/etc/firewalld/services/haproxy-http.xml
           backup=yes

    - name: start firewalld
      service: name=firewalld state=started

    - name: set SELinux on HAProxy-http
      command: restorecon /etc/firewalld/services/haproxy-http.xml
      command: chmod 640 /etc/firewalld/services/haproxy-http.xml

    - name: Update HAProxy config
      template: src=templates/haproxy.cfg 
            dest=/etc/haproxy/haproxy.cfg 
            backup=yes
      notify: 
        - restart haproxy

  handlers:
    - name: restart haproxy
      service: name=haproxy state=restarted
